version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: no
    environment:
      POSTGRES_SERVER: host.docker.internal
      POSTGRES_PORT: 5434
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    links:
      - db:db_domain
    depends_on:
      - db

  db:
    container_name: yandex-lavka-db
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  dbvolume:
